# Generated by Django 4.1 on 2022-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakarapp', '0008_submission_delete_taskone_delete_taskzero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=models.FileField(upload_to='doc/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='authentication',
            field=models.FileField(upload_to='doc/'),
        ),
    ]
