# Generated by Django 4.1 on 2022-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakarapp', '0009_alter_submission_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mobileNo',
            field=models.IntegerField(),
        ),
    ]
