# Generated by Django 4.1 on 2023-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aakarapp', '0010_alter_submission_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='iitb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('ldap', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='non_iitb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=200)),
                ('transaction_id', models.IntegerField()),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshot/')),
            ],
        ),
    ]
