# Generated by Django 4.1 on 2023-01-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cityplan_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1', models.CharField(max_length=200)),
                ('email1', models.CharField(max_length=100)),
                ('contact1', models.CharField(max_length=12)),
                ('participant2', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=100)),
                ('contact2', models.CharField(max_length=12)),
                ('participant3', models.CharField(max_length=200)),
                ('email3', models.CharField(max_length=100)),
                ('contact3', models.CharField(max_length=12)),
                ('participant4', models.CharField(max_length=200)),
                ('email4', models.CharField(max_length=100)),
                ('contact4', models.CharField(max_length=12)),
                ('ref', models.CharField(max_length=50)),
            ],
        ),
    ]
