# Generated by Django 4.1 on 2022-12-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poster_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('mail1', models.CharField(max_length=200)),
                ('mobile1', models.IntegerField()),
                ('college', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=50)),
                ('mail2', models.CharField(max_length=200)),
                ('mobile2', models.IntegerField()),
                ('name3', models.CharField(max_length=50)),
                ('mobile3', models.IntegerField()),
                ('mail3', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('others', models.CharField(max_length=100)),
            ],
        ),
    ]
