# Generated by Django 4.1 on 2023-02-04 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster_class',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
