# Generated by Django 4.1 on 2023-02-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0002_poster_class_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster_class',
            name='mobile1',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='poster_class',
            name='mobile2',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='poster_class',
            name='mobile3',
            field=models.CharField(max_length=25),
        ),
    ]
