# Generated by Django 4.1 on 2023-02-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_app', '0003_alter_poster_class_mobile1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster_class',
            name='experience',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poster_class',
            name='ref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
